#!/bin/bash -le
#PBS -l walltime=1:00:00
#PBS -o Output.job
#PBS -j oe
#PBS -l nodes=1:ppn=20
#PBS -M jakub.krajniak@cs.kuleuven.be
#PBS -A  lp_sim_interpoco

source switch_to_2015a

module purge
module load 2015a/espressopp/adress
module load bakery-github-dev

cd $PBS_O_WORKDIR

# Set up OpenMPI environment
n_proc=$(cat $PBS_NODEFILE | wc -l)
n_node=$(cat $PBS_NODEFILE | uniq | wc -l)
#mpdboot -f $PBS_NODEFILE -n $n_node -r ssh -v

LOG="${PBS_O_WORKDIR}/${PBS_JOBID}.log"

for alpha in 0.00001; do
    for s in {2..2}; do
        mkdir -p jump_s${s}
        #rng_seed=`shuf -n1 -i1000-10000`
        rng_seed=2047
        mpirun -n 18 start_backmapping.py @params --alpha $alpha --rng_seed $rng_seed --output_prefix jump_s${s}/sim0 --energy_collect 100 --energy_collect_bck 100 --gro_collect 100 --trj_collect 100 --long 10000 --skin 0.4 &> test_jump.log
    done
done
